# NOTE: why I use `-s` instead of `-g` flag see here:
# https://stackoverflow.com/questions/41783367/tmux-tmux-true-color-is-not-working-properly
# and here:
# https://superuser.com/questions/758843/difference-between-global-server-session-and-window-options
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

# shorten command delay
set -sg escape-time 0
set -g status-interval 0

# Change prefix
unbind C-b
set-option -g prefix C-x
set-option -g prefix2 C-Space

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Reorder tmux windows
# Pressing Ctrl+Shift+Left (will move the current windows to the left)
# Similarly right. No need to use modifier (C-x/C-Space)
bind -n C-S-Left swap-window -t -1\; select-window -t -1
bind -n C-S-Right swap-window -t +1\; select-window -t +1

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# resize panes using PREFIX H, J, K, L
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind f resize-pane -Z
bind e choose-window -Z

# set vi-mode
set-window-option -g mode-keys vi

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# taken from: https://github.com/gpakosz/.tmux/blob/master/.tmux.conf
bind-key Enter copy-mode # enter copy mode

# Middle click to paste from the clipboard
# I took it from: https://gist.github.com/rodricels/7951c3bd505d343b07309b76188af9b3
unbind-key MouseDown2Pane
bind-key -n MouseDown2Pane run "tmux set-buffer -- \"$(xclip -o -sel primary);\"; tmux paste-buffer -p"

# split pane and retain the current directory of existing pane or window
unbind '"'
bind-key v split-window -v -c "#{pane_current_path}"
unbind %
bind-key h split-window -h -c "#{pane_current_path}"

# Visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

# Set 'focus-events' ON as nvim is recomended
set-option -g focus-events on

# reload ~/.tmux.conf using PREFIX r
bind-key r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

set -g @catppuccin_flavour 'mocha'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
